import Head from "next/head";
import Navbar from "./api/src/components/Navbar/Navbar";
import GlobalStyle from "../styles/globals.css";
import { ThemeProvider } from "styled-components";
import { LightTheme } from "../styles/theme";
import styled from "styled-components";
import HomePage from "./api/src/components/Home/Home";
import About from "./api/src/components/About/About";

export default function Home() {
  return (
    <div>
      <ThemeProvider theme={LightTheme}>
        <GlobalStyle />
        <Head>
          <title>Mary Maina| Front-end developer</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="preconnect"
            href="https://fonts.googleapis.com"
            crossOrigin="anonymous"
          />

          <link
            rel="preload"
            href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&family=Poppins&family=Roboto:wght@300;400;500;700&display=swap"
            as="style"
          />

          <style
            dangerouslySetInnerHTML={{
              __html: `</style>
               <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&family=Poppins&family=Roboto:wght@300;400;500;700&display=swap"
    
      media="print"
      onload="this.media='all';"
    />
    <style>`,
            }}
          ></style>

          <noscript>
            <link
              href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&family=Poppins&family=Roboto:wght@300;400;500;700&display=swap"
              rel="stylesheet"
            />
          </noscript>
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin=""
          />
        </Head>
        <Navbar />
        <Container>
          <HomePage />
          <About />
        </Container>
      </ThemeProvider>
    </div>
  );
}

const Container = styled.div`
  padding: 0 32px;
   max-width: 1500px
  width: calc(100% - 64px);
`;
